[build]
builder = "NIXPACKS"
buildCommand = "./gradlew bootJar -x test"

[deploy]
startCommand = "java -jar build/libs/stitchbud-0.0.1-SNAPSHOT.jar"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
